org: fekarlstad23 ##CHANGE TO YOUR ORG
app: bonzai
service: awsbonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::597088039276:role/LambdaDynamoDBRole  ##CHANGE TO YOUR ROLE

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
