custom:
  localEnv: ${file(./local.yml)}

org: ${self:custom.localEnv.myOrg}
app: bonzai
service: awsbonzai

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${self:custom.localEnv.myLambdaArn}

functions:
  getRooms:
    handler: functions/getRooms/index.handler
    events:
      - httpApi:
          path: /rooms
          method: get
  bookRoom:
    handler: functions/bookRoom/index.handler
    events:
      - httpApi:
          path: /rooms
          method: post
  getOrder:
    handler: functions/getOrder/index.handler
    events:
      - httpApi:
          path: /orders/{id}
          method: get 
  getOrders:
    handler: functions/getOrders/index.handler
    events:
      - httpApi:
          path: /orders/admin
          method: get     
  cancelOrder:
    handler: functions/cancelOrder/index.handler
    events:
      - httpApi:
          path: /orders/{id}
          method: delete
  changeOrder:
    handler: functions/changeOrder/index.handler
    events:
      - httpApi:
          path: /orders/{id}
          method: put
  postRoom:
    handler: functions/postRoom/index.handler
    events:
      - httpApi:
          path: /room
          method: post

resources:
  Resources:
    RoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'rooms-db'
        AttributeDefinitions:
          - AttributeName: 'pk'
            AttributeType: 'S'
          - AttributeName: 'sk'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'pk'
            KeyType: 'HASH'
          - AttributeName: 'sk'
            KeyType: 'RANGE'
        BillingMode: PAY_PER_REQUEST
    RoomordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'roomorders-db'
        AttributeDefinitions:
          - AttributeName: 'pk'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'pk'
            KeyType: 'HASH'
        BillingMode: PAY_PER_REQUEST